version: '3'

services:
  # Spark Master
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
    networks:
      - spark-network
    ports:
      - "8081:8080"  # Spark UI
      - "7077:7077"  # Spark Master

  # Spark Worker node 1 (with Driver program)
  spark-worker-driver:
    image: bitnami/spark:latest
    container_name: spark-worker-driver
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2G
    networks:
      - spark-network
    volumes:
      - ./code:/opt/spark/work-dir  # Mount code into the container
      - ./.env:/opt/spark/.env  # Mount environment variables
      - ./google-key.json:/opt/spark/google-key.json  # Mount Google key
      - ./requirements.txt:/opt/spark/requirements.txt  # Mount requirements
      - ./start_date.txt:/opt/spark/start_date.txt  # Mount start date
      - ./jars/gcs-connector-hadoop3-latest.jar:/opt/bitnami/spark/jars/gcs-connector-hadoop3-latest.jar
      - ./jars/spark-bigquery-with-dependencies_2.12-0.36.1.jar:/opt/bitnami/spark/jars/spark-bigquery-with-dependencies_2.12-0.36.1.jar
    command: ["/bin/bash", "-c", "pip install -r /opt/spark/requirements.txt && spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077"]
    depends_on:
      - spark-master
    ports:
      - "4040:4040"  # Spark job UI for driver node

  # Spark Worker node 2
  spark-worker-2:
    image: bitnami/spark:latest
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2G
    volumes:
      - ./google-key.json:/opt/spark/google-key.json
    networks:
      - spark-network
    depends_on:
      - spark-master
    command: ["/bin/bash", "-c", "spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077"]

  # Spark Worker node 3
  spark-worker-3:
    image: bitnami/spark:latest
    container_name: spark-worker-3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2G
    volumes:
      - ./google-key.json:/opt/spark/google-key.json
    networks:
      - spark-network
    depends_on:
      - spark-master
    command: ["/bin/bash", "-c", "spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077"]

networks:
  spark-network:
    driver: bridge